on:
  pull_request:
    types: [review_requested]

jobs:
  genai_code_review:
    runs-on: ubuntu-latest
    name: GPT Code Review
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: GPT Code Review Testing
        uses: vsilvey/gpt-code-review@master
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GH_TOKEN }}
          github_pr_id: 1
          github_reviewer: 'sonargptreviewer'
          openai_model: 'o1-mini'
          openai_temperature: 0.5
          openai_max_tokens: 2048
          mode: patch # files or patch
          language: en # optional, default is 'en'
          custom_prompt: "" # optional
