on:
  pull_request:
    types: [review_requested]

jobs:
  genai_code_review:
    runs-on: ubuntu-latest
    name: GPT Code Review
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: GPT Code Review
        uses: vsilvey/gpt-code-review@master
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GH_TOKEN }}
          github_pr_id: 2 #${{ github.event.pull_request.number }}
          github_reviewer: 'sonargptreviewer' #${{ github.event.review.requested_reviewer.login }}
          openai_model: 'o1-mini'#'gpt-4o'
          openai_temperature: 1 #default value accepted by 'o1-mini'
          openai_max_tokens: 5000
